### ISSUE TITLE
I couldn't install sub-modules and libraries.

### ISSUE THREAD

**Issue by lnxpy** [siruidops/uidsploit#1]
Hey @siruidops,

I cloned your repo to start using it but I couldn't find anything like `install.py`. I prefer you use requirements file to store your libraries, modules, and whatever your project needs to get boot up.
Thanks.

**Comment by siruidops** [comment]
سلام
install.py 
باگ داره
و وقت هم نکردم درستش کنم
باید دستی کتابخونه هارو نصب کنین
